services:
  - type: web
    name: gutsBot
    env: node
    plan: starter
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: RENDER
        value: true
      - key: MONGODB_URI
        sync: false  # Configurar en dashboard
    healthCheckPath: /health